main: lijpe.spin.Main
name: DeLijpeSpinPlugin
version: 1.0
author: Meneer Arie
description: Moooi!
debug: true
commands:
  spin:
    description: Geeft alle commando's weer van De Lijpe Spin Plugin!
    usage: /spin
    permission: lijpelynn.spin
    permission-message: Jij mag dit niet doen met je kop!
  welkom:
    description: Heet een speler welkom.
    usage: /welkom <player>
    permission: lijpelynn.welkom
    permission-message: Jij mag dit niet doen met je kop!
  bedtijd:
    description: Stuurt naar iedereen een bericht dat het bedtijd is.
    usage: /bedtijd
    permission: lijpelynn.bedtijd
    permission-message: Jij mag dit niet doen met je kop!
  handalshoed:
    description: Zet het item dat je in je hand hebt als hoed van een speler. Hilarische prank.
    usage: /handalshoed <player>
    permission: lijpelynn.handalshoed
    permission-message: Jij mag dit niet doen met je kop!
  spreekals:
    description: Neem de tong over van een speler. Hilarische prank.
    usage: /spreekals <player> <text>
    permission: lijpelynn.spreekals
    permission-message: Jij mag dit niet doen met je kop!